# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import service as _service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='agent.proto',
  package='baidu.lumia',
  serialized_pb='\n\x0b\x61gent.proto\x12\x0b\x62\x61idu.lumia\"-\n\x0c\x44\x65viceStatus\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07healthy\x18\x02 \x01(\x08\"@\n\x0bMountStatus\x12\x0b\n\x03\x64\x65v\x18\x01 \x01(\t\x12\x13\n\x0bmount_point\x18\x02 \x01(\t\x12\x0f\n\x07mounted\x18\x03 \x01(\x08\"\x8b\x01\n\x0cMinionStatus\x12*\n\x07\x64\x65vices\x18\x01 \x03(\x0b\x32\x19.baidu.lumia.DeviceStatus\x12(\n\x06mounts\x18\x02 \x03(\x0b\x32\x18.baidu.lumia.MountStatus\x12\x10\n\x08\x64\x61tetime\x18\x04 \x01(\x03\x12\x13\n\x0b\x61ll_is_well\x18\x05 \x01(\x08\"\x13\n\x11QueryAgentRequest\"b\n\x12QueryAgentResponse\x12\x30\n\rminion_status\x18\x01 \x01(\x0b\x32\x19.baidu.lumia.MinionStatus\x12\x0e\n\x06status\x18\x02 \x01(\x05\x12\n\n\x02ip\x18\x03 \x01(\t2V\n\nLumiaAgent\x12H\n\x05Query\x12\x1e.baidu.lumia.QueryAgentRequest\x1a\x1f.baidu.lumia.QueryAgentResponseB\x06\x80\x01\x01\x90\x01\x01')




_DEVICESTATUS = _descriptor.Descriptor(
  name='DeviceStatus',
  full_name='baidu.lumia.DeviceStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='baidu.lumia.DeviceStatus.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='healthy', full_name='baidu.lumia.DeviceStatus.healthy', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=28,
  serialized_end=73,
)


_MOUNTSTATUS = _descriptor.Descriptor(
  name='MountStatus',
  full_name='baidu.lumia.MountStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dev', full_name='baidu.lumia.MountStatus.dev', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mount_point', full_name='baidu.lumia.MountStatus.mount_point', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mounted', full_name='baidu.lumia.MountStatus.mounted', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=75,
  serialized_end=139,
)


_MINIONSTATUS = _descriptor.Descriptor(
  name='MinionStatus',
  full_name='baidu.lumia.MinionStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='devices', full_name='baidu.lumia.MinionStatus.devices', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mounts', full_name='baidu.lumia.MinionStatus.mounts', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='datetime', full_name='baidu.lumia.MinionStatus.datetime', index=2,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='all_is_well', full_name='baidu.lumia.MinionStatus.all_is_well', index=3,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=142,
  serialized_end=281,
)


_QUERYAGENTREQUEST = _descriptor.Descriptor(
  name='QueryAgentRequest',
  full_name='baidu.lumia.QueryAgentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=283,
  serialized_end=302,
)


_QUERYAGENTRESPONSE = _descriptor.Descriptor(
  name='QueryAgentResponse',
  full_name='baidu.lumia.QueryAgentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='minion_status', full_name='baidu.lumia.QueryAgentResponse.minion_status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='baidu.lumia.QueryAgentResponse.status', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ip', full_name='baidu.lumia.QueryAgentResponse.ip', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=304,
  serialized_end=402,
)

_MINIONSTATUS.fields_by_name['devices'].message_type = _DEVICESTATUS
_MINIONSTATUS.fields_by_name['mounts'].message_type = _MOUNTSTATUS
_QUERYAGENTRESPONSE.fields_by_name['minion_status'].message_type = _MINIONSTATUS
DESCRIPTOR.message_types_by_name['DeviceStatus'] = _DEVICESTATUS
DESCRIPTOR.message_types_by_name['MountStatus'] = _MOUNTSTATUS
DESCRIPTOR.message_types_by_name['MinionStatus'] = _MINIONSTATUS
DESCRIPTOR.message_types_by_name['QueryAgentRequest'] = _QUERYAGENTREQUEST
DESCRIPTOR.message_types_by_name['QueryAgentResponse'] = _QUERYAGENTRESPONSE

class DeviceStatus(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DEVICESTATUS

  # @@protoc_insertion_point(class_scope:baidu.lumia.DeviceStatus)

class MountStatus(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MOUNTSTATUS

  # @@protoc_insertion_point(class_scope:baidu.lumia.MountStatus)

class MinionStatus(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MINIONSTATUS

  # @@protoc_insertion_point(class_scope:baidu.lumia.MinionStatus)

class QueryAgentRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _QUERYAGENTREQUEST

  # @@protoc_insertion_point(class_scope:baidu.lumia.QueryAgentRequest)

class QueryAgentResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _QUERYAGENTRESPONSE

  # @@protoc_insertion_point(class_scope:baidu.lumia.QueryAgentResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\200\001\001\220\001\001')

_LUMIAAGENT = _descriptor.ServiceDescriptor(
  name='LumiaAgent',
  full_name='baidu.lumia.LumiaAgent',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=404,
  serialized_end=490,
  methods=[
  _descriptor.MethodDescriptor(
    name='Query',
    full_name='baidu.lumia.LumiaAgent.Query',
    index=0,
    containing_service=None,
    input_type=_QUERYAGENTREQUEST,
    output_type=_QUERYAGENTRESPONSE,
    options=None,
  ),
])

class LumiaAgent(_service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _LUMIAAGENT
class LumiaAgent_Stub(LumiaAgent):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _LUMIAAGENT

# @@protoc_insertion_point(module_scope)
